### ISSUE TITLE
sharing eml files with attachments results in Internal Server Error

### ISSUE THREAD

**Issue by jalbstmeijer** [newroco/emlviewer#38]
Using:

NC 23.0.3
Eml Viewer 1.0.1

When I share eml files that contains attachments, the viewer of that share ill get a Internal Server Error when trying to open/download the attachment.
```
Could not find file: /comunidad/test.eml
/var/www/html/custom_apps/emlviewer/lib/Storage/AuthorStorage.php
24

Trace
#0 /var/www/html/custom_apps/emlviewer/lib/Controller/PageController.php(287): OCA\EmlViewer\Storage\AuthorStorage->emlFileContent('/comunidad/test...')
#1 /var/www/html/custom_apps/emlviewer/lib/Controller/PageController.php(44): OCA\EmlViewer\Controller\PageController->parseEml()
#2 /var/www/html/custom_apps/emlviewer/lib/Controller/PageController.php(239): OCA\EmlViewer\Controller\PageController->getMessage()
#3 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(217): OCA\EmlViewer\Controller\PageController->attachment()
#4 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(126): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\EmlViewer\Controller\PageController), 'attachment')
#5 /var/www/html/lib/private/AppFramework/App.php(157): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\EmlViewer\Controller\PageController), 'attachment')
#6 /var/www/html/lib/private/Route/Router.php(302): OC\AppFramework\App::main('OCA\\EmlViewer\\C...', 'attachment', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#7 /var/www/html/lib/base.php(1006): OC\Route\Router->match('/apps/emlviewer...')
#8 /var/www/html/index.php(36): OC::handleRequest()
#9 {main}
```

**Comment by jalbstmeijer** [comment]
Looks like this issue was reported before and fixed, so probably the issue was re-introduced with NC 23.

https://github.com/newroco/emlviewer/issues/31
